/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'warm-bg': '#fefdfb',
        'primary': {
          DEFAULT: '#e4912a',
          hover: '#cf7318',
          light: '#eca94e',
          lighter: '#f4c682',
          lightest: '#f9deb3',
          dark: '#ab5614',
          darker: '#8c4416',
        },
        'jade': {
          DEFAULT: '#3aaa82',
          light: '#8bd5b7',
          lighter: '#bbe6d2',
          lightest: '#dcf3e6',
          dark: '#2e8b6a',
        },
        'cinnabar': {
          DEFAULT: '#d94444',
          light: '#f29e9e',
          lighter: '#fde4e4',
          dark: '#a32828',
        },
        'ochre': {
          DEFAULT: '#e8b525',
          light: '#f7dd8a',
          lighter: '#fbedb9',
        },
        'warm-sand': {
          DEFAULT: '#e6b982',
          light: '#f5e2c5',
          dark: '#b1834c',
        },
        'warm-cream': '#fefdfb',
        'warm-ivory': '#fdf9f1',
        'neutral': {
          50: '#faf9f7',
          100: '#f3f1ed',
          200: '#e7e3dc',
          300: '#d4cdc2',
          400: '#b0a596',
          500: '#948777',
          600: '#7a6d5e',
          700: '#63584c',
          800: '#524a41',
          900: '#453f38',
        },
        'surface': {
          DEFAULT: '#ffffff',
          raised: '#faf9f7',
          sunken: '#f3f1ed',
        },
        'border-custom': {
          DEFAULT: '#e7e3dc',
          light: '#f3f1ed',
        },
        'sand': '#e6b982',
        'sand-light': '#f5e2c5',
        'lavender': '#9B8AA6',
        'lavender-light': '#C4B8CC',
        'accent': '#D96B5C',
        'accent-light': '#E89A8F',
        'success': '#3aaa82',
        'text-main': '#453f38',
        'text-secondary': '#7a6d5e',
        'text-muted': '#948777',
        'border': '#e7e3dc',
        'card': '#FFFFFF',
      },
      fontFamily: {
        display: ['"Noto Serif SC"', 'serif'],
        body: ['"DM Sans"', '"PingFang SC"', '"Microsoft YaHei"', 'sans-serif'],
        sans: [
          '"DM Sans"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          'sans-serif',
        ],
      },
      borderRadius: {
        'card': '16px',
        'btn': '9999px',
        'sm': '6px',
        'md': '10px',
        'lg': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 1px 3px rgba(69, 63, 56, 0.04), 0 1px 2px rgba(69, 63, 56, 0.03)',
        'md': '0 4px 8px -2px rgba(69, 63, 56, 0.05)',
        'lg': '0 8px 24px -4px rgba(69, 63, 56, 0.05)',
        'float': '0 16px 40px -8px rgba(69, 63, 56, 0.20)',
        'primary-glow': '0 4px 16px rgba(228, 145, 42, 0.35)',
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'base': '16px',
        'lg': '18px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
      },
      lineHeight: {
        'tight': '1.2',
        'normal': '1.6',
        'relaxed': '1.8',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '24px',
        '6': '32px',
        '7': '48px',
        '8': '64px',
      },
    },
  },
  plugins: [],
}
